# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_owner_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=3)),
                ('address', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField(max_length=10)),
                ('car_name', models.CharField(max_length=15)),
                ('car_number', models.CharField(max_length=10)),
            ],
        ),
    ]
