# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_members', '0002_auto_20170506_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='members',
            name='mobile_number',
            field=models.IntegerField(default=0),
        ),
    ]
